/*
	Falcon.js
	by Rick Allen (stoodder)

	Version {{VERSION}}
	Full source at https://github.com/stoodder/falconjs
	Copyright (c) 2013 Rick Allen, http://www.stoodder.com

	MIT License, https://github.com/stoodder/falconjs/blob/master/LICENSE.md
	This file is generated by `cake build`, do not edit it by hand.
*/
/*
	Knockout JavaScript library v2.2.1
	(c) Steven Sanderson - http://knockoutjs.com/
	License: MIT (http://www.opensource.org/licenses/mit-license.php)
*/